---
title: "Energy Equity Residential Energy Consumption"
author: "Audrey Smith"
date: 5/8/2020"
output: html_document
---

_Setting up .rmd file_
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Librarying Packages
```{r}
library(tidyverse)
library(survey)
library(fastDummies)
library(sf)
library(data.table)
library(MASS)
options(scipen=999)
```

#Read in Data
```{r - Read RECS data and set study design}
#Reading in RECS data
recs15 <- read.csv('RECS/recs2015_clean.csv')

#Generating weight and rep weights
recsWeights <- recs15$NWEIGHT
recsBrr <- recs15[,grepl('^BRRWT', colnames(recs15))] #Grabbing all columns with Brr weights
recsBrrCol <- colnames(recsBrr) #Getting names of all columns containing Brr weights for later column selection

#Setting survey design
recsDes <- svrepdesign(weights = recsWeights, repweights = recsBrr, type = 'Fay', rho = .5, mse = TRUE, data = recs15) #Fay = resample method, Rho = weight shrinkage
```

```{r - Read in ACS Data}
tractPreds <- read.csv('predictors/ACSclimate_clean.csv') %>% dplyr::select(-X)
tractGeom <- read_sf('predictors/ACS_climateZones_int.shp') %>% dplyr::select(GISJOIN, geometry)

#Need to figure out why so many NAs
tractPreds <- drop_na(tractPreds)
```

#Plotting Response Variables
```{r}
#Electricity
svyhist(~KWH, recsDes)
svyhist(~log(KWH+.0000001), recsDes)
svyhist(~sqrt(KWH), recsDes)

#Natural Gas
svyhist(~CUFEETNG, recsDes)
svyhist(~log(CUFEETNG+.000001), recsDes)
svyhist(~sqrt(CUFEETNG), recsDes)

#Liquid Propane
svyhist(~GALLONLP, recsDes)
svyhist(~log(GALLONLP+.0000001), recsDes)
svyhist(~sqrt(GALLONLP), recsDes)

#Fuel Oil
svyhist(~GALLONFO, recsDes)
svyhist(~log(GALLONFO + .0000001), recsDes)
svyhist(~sqrt(GALLONFO), recsDes)

#Wood
svyhist(~WOODAMT, recsDes)
svyhist(~log(WOODAMT + .0000001), recsDes)
svyhist(~sqrt(WOODAMT), recsDes)
```

## Log Models by Fuel Type
```{r}
## ELECTRICITY
elecLog_full <- svyglm(log(BTUEL+.0000000001) ~ DIVISION_8 + CLIMATE_HOTDRY + FUELHEAT_1 + FUELHEAT_2 + FUELHEAT_5 + FUELHEAT_7 + HDD65 + CDD65 + HHAGE + HHSEX_1 + NHSLDMEM + NHSLDMEMSQ + NUMCHILD + EMPLOYHH_12 + SDESCENT_1 + MONEYPY_2 + MONEYPY_3 + MONEYPY_45 + MONEYPY_678 + HOUSEHOLDER_RACE_2 + HOUSEHOLDER_RACE_3 + HOUSEHOLDER_RACE_4 + HOUSEHOLDER_RACE_5 + HOUSEHOLDER_RACE_7 + TOTROOMS + YEARMADERANGE_2 + YEARMADERANGE_3 + YEARMADERANGE_4 + YEARMADERANGE_5 + YEARMADERANGE_6 + YEARMADERANGE_7 + YEARMADERANGE_8 + TYPEHUQ_1 + TYPEHUQ_3 + TYPEHUQ_4 + TYPEHUQ_5 + ELPAY_1 + HEATHOME, family = gaussian(identity), design = recsDes)

elecLog <- stepAIC(object = elecLog_full, direction = 'backward', trace = F)
elecLog_MSE <- c(crossprod(elecLog$residuals))/length(elecLog$residuals)

predict_elecLog <- as.data.frame(predict(object = elecLog, newdata = tractPreds, type = 'response', na.action = na.include))

predict_elecLog$BTUelec <- 1000*exp(predict_elecLog$response)

## NATURAL GAS
ngLog_full <- svyglm(log(BTUNG+.0000000001) ~ DIVISION_8 + CLIMATE_HOTDRY + FUELHEAT_1 + FUELHEAT_2 + FUELHEAT_5 + FUELHEAT_7 + HDD65 + CDD65 + HHAGE + HHSEX_1 + NHSLDMEM + NHSLDMEMSQ + NUMCHILD + EMPLOYHH_12 + SDESCENT_1 + MONEYPY_2 + MONEYPY_3 + MONEYPY_45 + MONEYPY_678 + HOUSEHOLDER_RACE_2 + HOUSEHOLDER_RACE_3 + HOUSEHOLDER_RACE_4 + HOUSEHOLDER_RACE_5 + HOUSEHOLDER_RACE_7 + TOTROOMS + YEARMADERANGE_2 + YEARMADERANGE_3 + YEARMADERANGE_4 + YEARMADERANGE_5 + YEARMADERANGE_6 + YEARMADERANGE_7 + YEARMADERANGE_8 + TYPEHUQ_1 + TYPEHUQ_3 + TYPEHUQ_4 + TYPEHUQ_5 + ELPAY_1 + HEATHOME, family = gaussian(identity), design = recsDes)

ngLog <- stepAIC(object = ngLog_full, direction = 'backward', trace = F)
ngLog_MSE <- c(crossprod(ngLog$residuals))/length(ngLog$residuals)

predict_ngLog <- as.data.frame(predict(object = ngLog, newdata = tractPreds, type = 'response', na.action = na.exclude))
predict_ngLog$BTUng <- 1000*exp(predict_ngLog$response)

## LIQUID PROPANE GAS
lpgLog_full <- svyglm(log(BTULP+.0000000001) ~ DIVISION_8 + CLIMATE_HOTDRY + FUELHEAT_1 + FUELHEAT_2 + FUELHEAT_5 + FUELHEAT_7 + HDD65 + CDD65 + HHAGE + HHSEX_1 + NHSLDMEM + NHSLDMEMSQ + NUMCHILD + EMPLOYHH_12 + SDESCENT_1 + MONEYPY_2 + MONEYPY_3 + MONEYPY_45 + MONEYPY_678 + HOUSEHOLDER_RACE_2 + HOUSEHOLDER_RACE_3 + HOUSEHOLDER_RACE_4 + HOUSEHOLDER_RACE_5 + HOUSEHOLDER_RACE_7 + TOTROOMS + YEARMADERANGE_2 + YEARMADERANGE_3 + YEARMADERANGE_4 + YEARMADERANGE_5 + YEARMADERANGE_6 + YEARMADERANGE_7 + YEARMADERANGE_8 + TYPEHUQ_1 + TYPEHUQ_3 + TYPEHUQ_4 + TYPEHUQ_5 + ELPAY_1 + HEATHOME, family = gaussian(identity), design = recsDes)

lpgLog <- stepAIC(object = lpgLog_full, direction = 'backward', trace = F)
lpgLog_MSE <- c(crossprod(lpgLog$residuals))/length(lpgLog$residuals)

predict_lpgLog <- as.data.frame(predict(object = lpgLog, newdata = tractPreds, type = 'response', na.action = na.exclude))
predict_lpgLog$BTUlpg <- 1000*exp(predict_lpgLog$response)

## FUEL OIL
foLog_full <- svyglm(log(BTUFO+.0000000001) ~ DIVISION_8 + CLIMATE_HOTDRY + FUELHEAT_1 + FUELHEAT_2 + FUELHEAT_5 + FUELHEAT_7 + HDD65 + CDD65 + HHAGE + HHSEX_1 + NHSLDMEM + NHSLDMEMSQ + NUMCHILD + EMPLOYHH_12 + SDESCENT_1 + MONEYPY_2 + MONEYPY_3 + MONEYPY_45 + MONEYPY_678 + HOUSEHOLDER_RACE_2 + HOUSEHOLDER_RACE_3 + HOUSEHOLDER_RACE_4 + HOUSEHOLDER_RACE_5 + HOUSEHOLDER_RACE_7 + TOTROOMS + YEARMADERANGE_2 + YEARMADERANGE_3 + YEARMADERANGE_4 + YEARMADERANGE_5 + YEARMADERANGE_6 + YEARMADERANGE_7 + YEARMADERANGE_8 + TYPEHUQ_1 + TYPEHUQ_3 + TYPEHUQ_4 + TYPEHUQ_5 + ELPAY_1 + HEATHOME, family = gaussian(identity), design = recsDes)

foLog <- stepAIC(object = foLog_full, direction = 'backward', trace = F)
foLog_MSE <- c(crossprod(foLog$residuals))/length(foLog$residuals)

predict_foLog <- as.data.frame(predict(object = foLog, newdata = tractPreds, type = 'response', na.action = na.exclude))
predict_foLog$BTUfo <- 1000*exp(predict_foLog$response)

## WOOD
woodLog_full <- svyglm(log(WOODBTU+.0000000001) ~ DIVISION_8 + CLIMATE_HOTDRY + FUELHEAT_1 + FUELHEAT_2 + FUELHEAT_5 + FUELHEAT_7 + HDD65 + CDD65 + HHAGE + HHSEX_1 + NHSLDMEM + NHSLDMEMSQ + NUMCHILD + EMPLOYHH_12 + SDESCENT_1 + MONEYPY_2 + MONEYPY_3 + MONEYPY_45 + MONEYPY_678 + HOUSEHOLDER_RACE_2 + HOUSEHOLDER_RACE_3 + HOUSEHOLDER_RACE_4 + HOUSEHOLDER_RACE_5 + HOUSEHOLDER_RACE_7 + TOTROOMS + YEARMADERANGE_2 + YEARMADERANGE_3 + YEARMADERANGE_4 + YEARMADERANGE_5 + YEARMADERANGE_6 + YEARMADERANGE_7 + YEARMADERANGE_8 + TYPEHUQ_1 + TYPEHUQ_3 + TYPEHUQ_4 + TYPEHUQ_5 + ELPAY_1 + HEATHOME, family = gaussian(identity), design = recsDes)

woodLog <- stepAIC(object = woodLog_full, direction = 'backward', trace = F)
woodLog_MSE <- c(crossprod(woodLog$residuals))/length(woodLog$residuals)

predict_woodLog <- as.data.frame(predict(object = woodLog, newdata = tractPreds, type = 'response', na.action = na.exclude))
predict_woodLog$BTUwood <- 1000*exp(predict_woodLog$response)
```

_All Fuels_
```{r}
predict_allLog <- as.data.frame(cbind(tractPreds[,c(1, 14, 19, 18)], predict_elecLog, predict_ngLog, predict_lpgLog, predict_foLog, predict_woodLog))
predict_allLog <- predict_allLog[, c(1:4, 7, 10, 13, 16, 19)]
expected <- c(343000000000000, 165000000000000, 112000000000000)

validation <- predict_allLog %>%
  mutate(BTUtract = TOTALHH*(BTUelec + BTUng + BTUlpg + BTUfo + BTUwood)) %>%
  group_by(state_code) %>%
  summarize(BTUstate = 1.115*sum(BTUtract)) %>% #1.115 assumes there is no pattern to the NAs and accounts for the 11% of rows that are presently missing from pred data
  mutate(BTUexpected = expected, propError = (BTUexpected-BTUstate)/BTUexpected)

validation
```
